pd

diff --git a/automation/Dockerfile b/automation/Dockerfile
--- a/automation/Dockerfile
+++ b/automation/Dockerfile
@@ -19,11 +19,11 @@ RUN apt-get -y install systemctl openvpn
 
 RUN systemctl enable --now openvpn
 RUN systemctl daemon-reload
-RUN systemctl status openvpn && echo 'suppress errors'
+RUN systemctl status openvpn || echo 'suppress errors'
 
 #install ansible
 RUN apt-get -y install ansible
 
 RUN echo "test"
 #clear space
-RUN rm -rf /var/lib/apt/lists/* || apt-get clean && apt-get autoremove -y
+RUN rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get autoremove -y
